#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "defines.h"
#include "structs.h"
#include "globals.h"
#include "init_model.h"
#include "shared_functions.h"
#include "merge_obj_vertices.h"
#include "merge_faces.h"
#include "merge_obj_faces.h"
#include "remove_t_junctions.h"
#include "subdiv_lut.h"
#include "make_grid.h"
#include "grid_clipping.h"
#include "grid.h"
#include "face_vt_list.h"
#include "math_c.h"
#include "utils.h"
#include "list.h"