void set_objects_size(model_t *model);
void sort_objects(model_t *model);
void center_objects(model_t *model);
void make_sprites(object_t *object);
void set_type_vt(object_t *object);
void make_txcoords_positive(object_t *object);
void resize_txcoords(object_t *object, textures_t *textures);
void merge_mdl_txcoords(object_t *object);
void subdivide_faces_into_quads(object_t *object);
void convert_to_fixed(object_t *object);
void adjust_txcoords_max_size(object_t *object);
void set_face_angles(object_t *object);