void memset16(void *dst, s16 val, uint count);
void memset32(void *dst, s32 val, uint count);
void memcpy16(void *dst, const void *src, uint count);
void memcpy32(void *dst, const void *src, uint count);
void set_poly_from_obj_vertices(int face_id, poly_t *poly, object_t *object);
void make_poly_aabb(aabb_t *aabb, poly_t *poly);
void make_poly_tx_aabb(tx_aabb_t *aabb, poly_t *poly);
void make_object_aabb(aabb_t *aabb, object_t *object);
void print_model_face(int face_id, object_t *object);
int clamp_i(int x, int min, int max);
int count_bits(int n);
int log2_c(int n);
int test_loop(int *input, int count);