#include "defines.h"

#include <stdio.h>
#include <stdlib.h>
#include "pc.h"
#include "gdi.h"

#include "custom_defines.h"
#include "engine_structs.h"
#include "scene_structs.h"
#include "engine_defines.h"
#include "scene_defines.h"
#include "game_defines.h"
#include "list.h"

#include "engine_globals.h"
#include "scene_globals.h"

#include "init.h"
#include "init_model.h"
#include "update_scene.h"

#include "draw.h"
// #include "game/draw_cursor.h"
#include "game.h"

#include "engine_init.h"
#include "scene.h"
#include "draw_scene.h"
#include "scene_setup.h"
#include "import_files.h"
#include "export_files.h"

#include "engine/math_c.h"
#include "engine/utils.h"
#include "engine/div_lut.h"
#include "engine/subdiv_lut.h"
#include "engine/lut.h"
#include "engine/clipping.h"
#include "engine/subdiv_face.h"
#include "engine/frustum.h"
#include "engine/matrix.h"
#include "engine/setup.h"
#include "engine/transforms.h"
#include "engine/visibility.h"
#include "engine/process_faces.h"
#include "engine/drawing.h"
#include "engine/raster.h"
#include "engine/raster_zb.h"
#include "engine/raster_occ.h"
#include "engine/raster_occ_zb.h"
#include "engine/render_voxel.h"
#include "engine/frustum_cl_grid.h"
#include "engine/font.h"
#include "engine/text.h"